### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by Michel-FK** [mangopi-sbc/MQ-Dual#1]
This board looks very interesting!

As the T113-S3 seems to be pin-to-pin compatible with the Risc V D1/F133-A, it looks like the board can actually support either chip.

I see that a crowdfunding campaign is planned on CrowdSupply for the MangoPi Nezha-MQ board (https://www.crowdsupply.com/rt-thread/mangopi-nezha-mq), will it also cover the T114-S3-based MangoPi MQ-Dual as well? Any date yet?

As a suggestion, I would like to see an AXP PMIC instead of the RY1303 in order to provide a DC/DC battery charger and Coulomb counter for battery operation.

**Comment by mangobuge** [comment]
Thanks for attention!
I think there is no need for crowdfunding for the ARM version of MQ . We will directly produce a batch. It is expected that aliexpress and dfrobot will be available next month. : )
